### ISSUE TITLE
start.sh uses hostname -i thereby assuming GNU hostname

### ISSUE THREAD

**Issue by dekobon** [tgross/triton-touchbase#14]
Please review this line:
https://github.com/tgross/triton-touchbase/blob/f787bafb3e56cb983422086f84e92653d504fdc3/start.sh#L55

This causes the script to fail on OS X. A PR will soon follow.

**Comment by tgross** [comment]
> This causes the script to fail on OS X

Only when you're hitting the local Docker but not using `docker-machine` with the default machine. But yeah, it's a bug.

**Comment by dekobon** [comment]
The host substitution tries to happen regardless of using local docker or not. I was testing against us-east-3b.

**Comment by tgross** [comment]
Ok then to be specific the hostname substitution only happens if `ip` is not set. i.e. either you're on Triton but you're failing to get the IP of the container, or you're on local and failing to get the IP for Docker Machine.

``` bash
#!/bin/bash

doStuff() {
    ip=x
    echo "${ip:-`hostname -i`}"
}

doStuff
```

So yes it's a bug, but that's just masking the real problem which is that something gone awry with the container you're trying to get the IP for.

**Comment by dekobon** [comment]
Thanks for clarifying.

**Comment by tgross** [comment]
@dekobon has this been sufficiently fixed by asserting the environment in https://github.com/tgross/triton-touchbase/pull/16 ?

**Comment by dekobon** [comment]
Yeah, go ahead and close once we merge.

**Comment by tgross** [comment]
Closing as https://github.com/tgross/triton-touchbase/pull/16 was merged.
